//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumentStorage
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public Document()
        {
            this.Revisions = new HashSet<Revision>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
        public string author { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual ICollection<Revision> Revisions { get; set; }
    }
}
