//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTests.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IDocumentsService")]
    public interface IDocumentsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentsService/CreateDocument", ReplyAction="http://tempuri.org/IDocumentsService/CreateDocumentResponse")]
        System.IO.Stream CreateDocument(System.IO.Stream adv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentsService/GetDocuments", ReplyAction="http://tempuri.org/IDocumentsService/GetDocumentsResponse")]
        System.IO.Stream GetDocuments();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentsService/GetDocument", ReplyAction="http://tempuri.org/IDocumentsService/GetDocumentResponse")]
        System.IO.Stream GetDocument(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentsService/GetDocumentMetadata", ReplyAction="http://tempuri.org/IDocumentsService/GetDocumentMetadataResponse")]
        System.IO.Stream GetDocumentMetadata(string id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDocumentsServiceChannel : UnitTests.ServiceReference1.IDocumentsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DocumentsServiceClient : System.ServiceModel.ClientBase<UnitTests.ServiceReference1.IDocumentsService>, UnitTests.ServiceReference1.IDocumentsService {
        
        public DocumentsServiceClient() {
        }
        
        public DocumentsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DocumentsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocumentsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocumentsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.IO.Stream CreateDocument(System.IO.Stream adv) {
            return base.Channel.CreateDocument(adv);
        }
        
        public System.IO.Stream GetDocuments() {
            return base.Channel.GetDocuments();
        }
        
        public System.IO.Stream GetDocument(string id) {
            return base.Channel.GetDocument(id);
        }
        
        public System.IO.Stream GetDocumentMetadata(string id) {
            return base.Channel.GetDocumentMetadata(id);
        }
    }
}
