//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.7.2558.0.
// 

using System;
using System.Xml.Serialization;

namespace Vokabular.Marc21ProjectParser
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
    [Serializable()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace = "http://www.loc.gov/MARC21/slim")]
    [XmlRoot("record", Namespace = "http://www.loc.gov/MARC21/slim", IsNullable = true)]
    public partial class MARC21record
    {

        private leaderFieldType leaderField;

        private controlFieldType[] controlfieldField;

        private dataFieldType[] datafieldField;

        private recordTypeType typeField;

        private bool typeFieldSpecified;

        private string idField;

        /// <remarks/>
        public leaderFieldType leader
        {
            get { return this.leaderField; }
            set { this.leaderField = value; }
        }

        /// <remarks/>
        [XmlElement("controlfield")]
        public controlFieldType[] controlfield
        {
            get { return this.controlfieldField; }
            set { this.controlfieldField = value; }
        }

        /// <remarks/>
        [XmlElement("datafield")]
        public dataFieldType[] datafield
        {
            get { return this.datafieldField; }
            set { this.datafieldField = value; }
        }

        /// <remarks/>
        [XmlAttribute()]
        public recordTypeType type
        {
            get { return this.typeField; }
            set { this.typeField = value; }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool typeSpecified
        {
            get { return this.typeFieldSpecified; }
            set { this.typeFieldSpecified = value; }
        }

        /// <remarks/>
        [XmlAttribute(DataType = "ID")]
        public string id
        {
            get { return this.idField; }
            set { this.idField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
    [Serializable()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace = "http://www.loc.gov/MARC21/slim")]
    public partial class leaderFieldType
    {

        private string idField;

        private string valueField;

        /// <remarks/>
        [XmlAttribute(DataType = "ID")]
        public string id
        {
            get { return this.idField; }
            set { this.idField = value; }
        }

        /// <remarks/>
        [XmlText()]
        public string Value
        {
            get { return this.valueField; }
            set { this.valueField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
    [Serializable()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace = "http://www.loc.gov/MARC21/slim")]
    public partial class subfieldatafieldType
    {

        private string idField;

        private string codeField;

        private string valueField;

        /// <remarks/>
        [XmlAttribute(DataType = "ID")]
        public string id
        {
            get { return this.idField; }
            set { this.idField = value; }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string code
        {
            get { return this.codeField; }
            set { this.codeField = value; }
        }

        /// <remarks/>
        [XmlText()]
        public string Value
        {
            get { return this.valueField; }
            set { this.valueField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
    [Serializable()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace = "http://www.loc.gov/MARC21/slim")]
    public partial class dataFieldType
    {

        private subfieldatafieldType[] subfieldField;

        private string idField;

        private string tagField;

        private string ind1Field;

        private string ind2Field;

        /// <remarks/>
        [XmlElement("subfield")]
        public subfieldatafieldType[] subfield
        {
            get { return this.subfieldField; }
            set { this.subfieldField = value; }
        }

        /// <remarks/>
        [XmlAttribute(DataType = "ID")]
        public string id
        {
            get { return this.idField; }
            set { this.idField = value; }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string tag
        {
            get { return this.tagField; }
            set { this.tagField = value; }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string ind1
        {
            get { return this.ind1Field; }
            set { this.ind1Field = value; }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string ind2
        {
            get { return this.ind2Field; }
            set { this.ind2Field = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
    [Serializable()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace = "http://www.loc.gov/MARC21/slim")]
    public partial class controlFieldType
    {

        private string idField;

        private string tagField;

        private string valueField;

        /// <remarks/>
        [XmlAttribute(DataType = "ID")]
        public string id
        {
            get { return this.idField; }
            set { this.idField = value; }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string tag
        {
            get { return this.tagField; }
            set { this.tagField = value; }
        }

        /// <remarks/>
        [XmlText()]
        public string Value
        {
            get { return this.valueField; }
            set { this.valueField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
    [Serializable()]
    [XmlType(Namespace = "http://www.loc.gov/MARC21/slim")]
    public enum recordTypeType
    {

        /// <remarks/>
        Bibliographic,

        /// <remarks/>
        Authority,

        /// <remarks/>
        Holdings,

        /// <remarks/>
        Classification,

        /// <remarks/>
        Community,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
    [Serializable()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace = "http://www.loc.gov/MARC21/slim")]
    [XmlRoot("collection", Namespace = "http://www.loc.gov/MARC21/slim", IsNullable = true)]
    public partial class collectionType
    {

        private MARC21record[] recordField;

        private string idField;

        /// <remarks/>
        [XmlElement("record", IsNullable = true)]
        public MARC21record[] record
        {
            get { return this.recordField; }
            set { this.recordField = value; }
        }

        /// <remarks/>
        [XmlAttribute(DataType = "ID")]
        public string id
        {
            get { return this.idField; }
            set { this.idField = value; }
        }
    }
}