//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocProjectStorageWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DocProjectModelContainer : DbContext
    {
        public DocProjectModelContainer()
            : base("name=DocProjectModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DocProjectEntity> DocProjectEntities { get; set; }
        public DbSet<RevisionEntity> RevisionEntities { get; set; }
        public DbSet<MessageEntity> MessageEntities { get; set; }
        public DbSet<EditorEntity> EditorEntities { get; set; }
        public DbSet<UserEntity> UserEntities { get; set; }
        public DbSet<UserRoleEntity> UserRoleEntities { get; set; }
        public DbSet<EventEntity> EventEntities { get; set; }
        public DbSet<ProjectStateEntity> ProjectStateEntities { get; set; }
        public DbSet<DocumentType> DocumentTypes { get; set; }
    }
}
