//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocProjectStorageWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocProjectEntity
    {
        public DocProjectEntity()
        {
            this.Revisions = new HashSet<RevisionEntity>();
            this.Editors = new HashSet<EditorEntity>();
            this.Messages = new HashSet<MessageEntity>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
    
        public virtual ICollection<RevisionEntity> Revisions { get; set; }
        public virtual ICollection<EditorEntity> Editors { get; set; }
        public virtual ICollection<MessageEntity> Messages { get; set; }
        public virtual ProjectStateEntity ProjectState { get; set; }
        public virtual DocumentType Type { get; set; }
    }
}
