//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocProjectStorageWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventEntity
    {
        public int Id { get; set; }
        public System.DateTime OccurTime { get; set; }
        public string Type { get; set; }
    
        public virtual DocProjectEntity RelatedProject { get; set; }
        public virtual UserEntity RelatedUser { get; set; }
    }
}
