//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocProjectStorageWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RevisionEntity
    {
        public int Number { get; set; }
        public System.DateTime Released { get; set; }
        public byte[] DocxData { get; set; }
        public int Id { get; set; }
    }
}
