SET XACT_ABORT ON;
--USE ITJakubWebDB

ALTER DATABASE CURRENT
SET ALLOW_SNAPSHOT_ISOLATION ON

ALTER DATABASE CURRENT
SET READ_COMMITTED_SNAPSHOT ON WITH ROLLBACK IMMEDIATE



SET XACT_ABORT ON
BEGIN TRAN


	DROP TABLE [dbo].[DatabaseVersion];

    DROP TABLE [dbo].[StaticText];
        
    INSERT INTO [dbo].[DatabaseVersion]
		(DatabaseVersion)
	VALUES
		('002' )
		-- DatabaseVersion - varchar

--ROLLBACK
COMMIT